# import webbrowser
# import requests
from logging import error
from msilib.schema import Error
from pyexpat import ErrorString
import time
# from bs4 import BeautifulSoup
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 


class AutomateInsta():
    def __init__(self):
        chrome_path = r'C:/Program Files/Google/Chrome/Application/chrome.exe %s'
        url = 'https://www.instagram.com/?hl=en'

        options = webdriver.ChromeOptions()      

        options.add_experimental_option("detach", True)

        self.driver = webdriver.Chrome(chrome_options=options,executable_path="D:\API python\AutomateInsta_for_birthday\chromedriver.exe")
        self.driver.maximize_window()
        self.driver.get(url)
        self.firsttime = True
        time.sleep(3)
    
    def login_Into_Instagram(self,username,password):
        """ automate login to your instagram account if right username and password is provided."""

        print("\n..........logging into your Account..........\n")
        
        self.driver.find_element_by_css_selector(
            "#loginForm > div > div:nth-child(1) > div > label > input").send_keys(username)

        self.driver.find_element_by_xpath("//*[@id='loginForm']/div/div[2]/div/label/input").send_keys(password)

        submit = self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[3]')
        submit.click()


        time.sleep(6)

    def wishBirthday(self,name):
        url = f'https://www.instagram.com/{name}/?hl=en'
        
        self.driver.get(url)

        time.sleep(3)
        message_btn = self.driver.find_element_by_css_selector('#react-root > section > main > div > header > section > div.XBGH5 > div.qF0y9.Igw0E.IwRSH.eGOV_.ybXk5._4EzTm.bPdm3 > div > div.qF0y9.Igw0E.IwRSH.eGOV_.acqo5.vwCYk.soMvl.i0EQd > button')
        message_btn.click()

        time.sleep(3)
    
        try:
            # print(" THIS IS THE WINDOW_HANDLE ---->",self.driver.current_window_handle)
            notnow_notification = self.driver.find_element_by_xpath('/html/body/div[6]/div/div/div/div[3]/button[2]')
            notnow_notification.click()
        except:
            pass    
        time.sleep(3)
        message_textarea = self.driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea')
        message_textarea.send_keys("<message generated by BOT> ALL THE BEST -by Master Shrestha")
        # message_textarea.send_keys("❤️")

        time.sleep(2)

        send = self.driver.find_element_by_xpath('//*[@id="react-root"]/section/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/button')
        send.click()



